export const doctorPlans = [
  {
    amount: '1500',
    entity: '',
    oldAmount: '3000',
    name: 'Billed Monthly',
    code: '',
    per: '(Save \u20A61,500)',
    type: '',
    features: [
      'Free Aegle Account',
      'Access to handpicked doctors 24/7',
      'Specialists and therapists on demand',
      'Get prescriptions in minutes',
      'Medical and referal notes',
      'Medical follow-ups',
      'Add a family member less than 16 years',
      'Access to our cutting-edge symptom checker',
      'Access to our free digital health monitor',
      'Daily suggestions to improve mental health',
      'Mood journaling',
      'Health lounge key pass access',
      'Generous discount from our wellbeing partners',
    ],
  },
  {
    amount: '4000',
    entity: '',
    oldAmount: '7000',
    name: 'Billed Every 3 Months',
    code: '',
    per: '(Save \u20A63,000)',
    type: '',
    features: [
      'Free Aegle Account',
      'Access to handpicked doctors 24/7',
      'Specialists and therapists on demand',
      'Get prescriptions in minutes',
      'Medical and referal notes',
      'Medical follow-ups',
      'Add a family member less than 16 years',
      'Access to our cutting-edge symptom checker',
      'Access to our free digital health monitor',
      'Daily suggestions to improve mental health',
      'Mood journaling',
      'Health lounge key pass access',
      'Generous discount from our wellbeing partners',
    ],
  },
  {
    amount: '14000',
    entity: '',
    oldAmount: '36000',
    name: 'Billed Annually',
    code: '',
    per: '(Save \u20A622,000)',
    type: '',
    features: [
      'Free Aegle Account',
      'Access to handpicked doctors 24/7',
      'Specialists and therapists on demand',
      'Get prescriptions in minutes',
      'Medical and referal notes',
      'Medical follow-ups',
      'Add a family member less than 16 years',
      'Access to our cutting-edge symptom checker',
      'Access to our free digital health monitor',
      'Daily suggestions to improve mental health',
      'Mood journaling',
      'Health lounge key pass access',
      'Generous discount from our wellbeing partners',
    ],
  },
];
